version: "3.8"
services:
    jekyll:
        image: jekyll/jekyll
        volumes:
            - .:/srv/jekyll
        command: bash -c "bundle update && jekyll serve"
        ports:
            - 4000:4000
        environment:
            - JEKYLL_ROOTLESS=true